### ISSUE TITLE
Link the Docker containers

### ISSUE THREAD

**Issue by crossan007** [ChurchCRM/Docker#2]
Link the database and web app container so that the initial setup is not necessary, since the CRM Administrator is setting the password at the time he/she provisions the database.

See documentation here regarding linking docker containers and sharing environment variables;
http://www.shogan.co.uk/docker/deploying-a-simple-linked-container-web-app-with-docker/

**Comment by jaskipper** [comment]
I'm leaving this open because we need to figure out a more secure way of automatically setting up the database. Getting the ENV from the linked container turns out to me incredibly insecure, and it is not working in docker-compose V2 on. Docker is trying to get rid of that way of working, because of the security holes it causes.

**Comment by jaskipper** [comment]
Fixed w/ the .env file in #5
